# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 840bc327b469a1df9f4f36c081336cfd4f6e2f30e1b68cf5cbbb5c8d7df26cf05e8bd29d38c32b5b94b37d1fb5ecc6b26c64333cbfdd99c9a6c8681688bf928f

test:
  secret_key_base: 0a969c84f98e687b9ef676b21124cecb6c7dae621d3e2565702bf943b2be326b939c08dc56792175577e91de4cdaec9090331ab62343e2394f62739c8e373ab5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
